### ISSUE TITLE
Listener check optimization

### ISSUE THREAD

**Issue by viktorprogger** [yiisoft/yii-event#2]
As for now we are using `container->get()` for some cases to check if a listener is valid in `EventConfigurator::isCallable()`. It makes us absolutely sure our listeners are valid listeners. But this will take significant resources with a huge amount of listeners. How about to leave only `container->has()` check?

**Comment by thenotsoft** [comment]
`container->has()` guarantees that a class or alias exists, but does not guarantee that a method exists in this object

**Comment by viktorprogger** [comment]
Yeap. But `get` creates all the dependencies with all their dependencies just to check if listener is valid while there is no guarantee it's event will happen.

**Comment by roxblnfk** [comment]
We can just add dev mode or one-time check on command. Would it be any better?

**Comment by viktorprogger** [comment]
I'm for making such checks in tests only. Inclusion of some checks on dev/prod/etc. mode, getting objects from DI container and enything else is violation of "single responsibility" principle and perfomance decreasing.

**Comment by viktorprogger** [comment]
Another way is to implement two different configurators through an interface: one for dev mode with pre-checks, another - a fast one.

**Comment by yiiliveext** [comment]
```php
$eventConfig = require Builder::path('events-web', dirname(__DIR__));
if (getenv('APP_ENV') === 'dev') {
    $validator = $container->get(EventConfigValidator::class);
    $validator->validateConfig($eventConfig);
}
$eventConfigurator = $container->get(EventConfigurator::class);
$eventConfigurator->registerListeners($eventConfig);

```

**Comment by viktorprogger** [comment]
```php
    public function __construct(Provider $listenerProvider, ContainerInterface $container, ?EventConfiguratorValidatorInterface $validator = null)
    {
        $this->listenerProvider = $listenerProvider;
        $this->container = $container;
        $this->validator = $validator;
    }

    public function registerListeners(array $eventListeners): void
    {
        /////////////////////
        if ($this->validator !== null) {
            $this->validator->validateConfig($eventListeners);
        }
        ///////////////////
    }
```

**Comment by samdark** [comment]
I've seen some PRs about it merged. Is this one still valid?

**Comment by viktorprogger** [comment]
@samdark, yes, see https://github.com/yiisoft/yii-event/blob/315034d35b9353b9a24a37515086b79cf38092a9/src/EventConfigurator.php#L96

**Comment by samdark** [comment]
> But this will take significant resources with a huge amount of listeners.

@viktorprogger how significant?

**Comment by viktorprogger** [comment]
This check is made optional in #10
