### ISSUE TITLE
missing Config class

### ISSUE THREAD

**Issue by strorch** [yiisoft/yii-event#29]
this package need to use \Yiisoft\Config\Config class  (in config/web.php). can you please add it to composer suggestions or provide solution to work with composer-config-plugin?

**Comment by samdark** [comment]
https://github.com/yiisoft/docs/blob/master/guide/en/concept/configuration.md here it is. We're not adding config plugin to `composer.json` since it's not really required to work with the package. You may configure it manually.

**Comment by samdark** [comment]
An example of already configured everything is available at https://github.com/yiisoft/app

**Comment by strorch** [comment]
OK, thank you!
