### ISSUE TITLE
Move events group name to component params.

### ISSUE THREAD

**Issue by olegbaturin** [yiisoft/yii-event#61]
Move config group name for events to component params.

```
'yiisoft/event' => [
    'eventsGroup' => 'events-web',
],
```

`ListenerCollection::class => static fn (Factory $factory) => $factory->create($params['yiisoft/event']['eventsGroup']),`

### Additional info

https://github.com/yiisoft/yii-event/blob/d3f830018d86dfd5e7d15fc4a6997d9cc8fa1659/config/di-web.php#L11

**Comment by vjik** [comment]
Need to don't forget add docs to readme about this feature.

**Comment by vjik** [comment]
Done by #62
